hlky/stable-diffusion:
  - source: webui.py
    dest: scripts/webui.py
  - source: relauncher.py
    dest: scripts/relauncher.py
  - source: txt2img.yaml
    dest: txt2img.yaml
  - source: webui.yaml
    dest: configs/webui/webui.yaml
  - source: readme.md
    dest: readme.md
